apiVersion: v1
kind: Service
metadata:
  name: devops-assignment
spec:
  selector:
    app: devops-assignment
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-assignment
  template:
    metadata:
      labels:
        app: devops-assignment
    spec:
      containers:
      - name: devops-assignment
        image: devops-assignment:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /app
          name: app
        ports:
        - containerPort: 4444
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: demo-pvc-claim
